export default [
    "Gender",
    "Colour",
    "Size",
    "Brand",
    "Size Chart",
    "Fabric",
    "Strap Material",
    "Water Resistant",
    "Display",
    "Glass Material",
    "Sport Type",
    "Base Metal",
    "Plating",
    "Care Instructions",
    "Wash Type",
    "Weight",
    "Length",
    "Breadth",
    "Height",
    "Features",
    "Fabric Finish",
    "Material",
    "Material Finish",
    "Pattern",
    "Occasion",
    "Season",
    "Trend",
    "Fit",
    "Collar",
    "Neck",
    "Bundles",
    "Max Sale Quantity",
    "Hemline",
    "Lining",
    "Num Pockets",
    "Reversible",
    "Bottom Type",
    "Top Type",
    "Front Styling",
    "Sleeve Length",
    "Sweatshirt Type",
    "Fragile",
    "Liquid",
    "Hazardous",
    "Power Type",
    "Battery Life",
    "Bluetooth",
    "Call Function",
    "Heart Rate Monitor",
    "Pedometer",
    "Sleep Monitor",
    "SPO2 Monitor",
    "Warranty",
    "Buckle Material",
    "Buckle Type",
    "Waist Rise",
    "Socks Length",
    "Footwear Type",
    "Insole",
    "Sole Material",
    "Toe Shape",
    "Outsole",
    "Fasten Type",
    "Midsole",
    "Backpack Style",
    "Closure Type",
    "Stone Type",
    "Gem Type",
    "Dial Shape",
    "Frame Type",
    "Frame Shape",
    "Frame Colour",
    "Frame Size",
    "Frame Material",
    "Frame Style",
    "Face Shape",
    "Lens Material",
    "Lens Colour",
    "Laptop Compartment",
    "Strap Type",
    "Volume",
    "Lock Type",
    "Ornamentation",
    "Coverage",
    "Padding",
    "Seam",
    "Waist Band",
    "Sustainability",
    "Handcrafted",
    "Craftmark"
]