export default {
    "column_1": "Gender",
    "column_2": "Colour",
    "column_3": "Size",
    "column_4": "Brand",
    "column_5": "Size Chart",
    "column_6": "Fabric",
    "column_7": "Strap Material",
    "column_8": "Water Resistant",
    "column_9": "Display",
    "column_10": "Glass Material",
    "column_11": "Sport Type",
    "column_12": "Base Metal",
    "column_13": "Plating",
    "column_14": "Care Instructions",
    "column_15": "Wash Type",
    "column_16": "Weight",
    "column_17": "Length",
    "column_18": "Breadth",
    "column_19": "Height",
    "column_20": "Features",
    "column_21": "Fabric Finish",
    "column_22": "Material",
    "column_23": "Material Finish",
    "column_24": "Pattern",
    "column_25": "Occasion",
    "column_26": "Season",
    "column_27": "Trend",
    "column_28": "Fit",
    "column_29": "Collar",
    "column_30": "Neck",
    "column_31": "Bundles",
    "column_32": "Max Sale Quantity",
    "column_33": "Hemline",
    "column_34": "Lining",
    "column_35": "Num Pockets",
    "column_36": "Reversible",
    "column_37": "Bottom Type",
    "column_38": "Top Type",
    "column_39": "Front Styling",
    "column_40": "Sleeve Length",
    "column_41": "Sweatshirt Type",
    "column_42": "Fragile",
    "column_43": "Liquid",
    "column_44": "Hazardous",
    "column_45": "Power Type",
    "column_46": "Battery Life",
    "column_47": "Bluetooth",
    "column_48": "Call Function",
    "column_49": "Heart Rate Monitor",
    "column_50": "Pedometer",
    "column_51": "Sleep Monitor",
    "column_52": "SPO2 Monitor",
    "column_53": "Warranty",
    "column_54": "Buckle Material",
    "column_55": "Buckle Type",
    "column_56": "Waist Rise",
    "column_57": "Socks Length",
    "column_58": "Footwear Type",
    "column_59": "Insole",
    "column_60": "Sole Material",
    "column_61": "Toe Shape",
    "column_62": "Outsole",
    "column_63": "Fasten Type",
    "column_64": "Midsole",
    "column_65": "Backpack Style",
    "column_66": "Closure Type",
    "column_67": "Stone Type",
    "column_68": "Gem Type",
    "column_69": "Dial Shape",
    "column_70": "Frame Type",
    "column_71": "Frame Shape",
    "column_72": "Frame Colour",
    "column_73": "Frame Size",
    "column_74": "Frame Material",
    "column_75": "Frame Style",
    "column_76": "Face Shape",
    "column_77": "Lens Material",
    "column_78": "Lens Colour",
    "column_79": "Laptop Compartment",
    "column_80": "Strap Type",
    "column_81": "Volume",
    "column_82": "Lock Type",
    "column_83": "Ornamentation",
    "column_84": "Coverage",
    "column_85": "Padding",
    "column_86": "Seam",
    "column_87": "Waist Band",
    "column_88": "Sustainability",
    "column_89": "Handcrafted",
    "column_90": "Craftmark"
}