export default [
    "Shirts",
    "T Shirts",
    "Sweatshirts",
    "Kurtas & Kurta Sets",
    "Jackets & Coats",
    "Sweaters",
    "Suits",
    "Sherwanis",
    "Track Shirts",
    "Track Suits",
    "Unstitched Fabrics",
    "Dresses",
    "Tops",
    "Trousers & Capris",
    "Coordinates",
    "Playsuits",
    "Jumpsuits",
    "Shrugs & Blouses",
    "Blazers & Waistcoats",
    "Tights, Leggings & Jeggings",
    "Track Pants",
    "Jeans",
    "Shorts",
    "Joggers",
    "Dhotis & Dhoti Pants",
    "Churidars",
    "Salwars",
    "Dungarees & Jumpsuits",
    "Skirts",
    "Clothing Sets",
    "Kurtis, Tunics",
    "Sarees",
    "Ethnic Wear",
    "Skirts & Palazzos",
    "Dress Materials",
    "Lehenga Cholis",
    "Dupattas & Shawls",
    "Burqas & Hijabs",
    "Blouses",
    "Blouse Pieces",
    "Briefs",
    "Boxers",
    "Vests",
    "Robes",
    "Night Suits",
    "Thermal Wear",
    "Swim Bottoms",
    "Swimwear",
    "Bra",
    "Shapewear",
    "Sleepwear & Loungewear",
    "Camisoles",
    "Lingerie Sets & Accessories",
    "Bath Robes",
    "Towels",
    "Pyjamas",
    "Party Wear",
    "Innerwear & Sleepwear",
    "Nightwear & Loungewear",
    "Watches",
    "Gloves",
    "Socks",
    "Stockings",
    "Laces",
    "Soles & Charms",
    "Shoe Racks & Organisers",
    "Shoe Care - Accessories",
    "Flip-Flops & Flats",
    "Sandals & Floaters",
    "Backpacks",
    "Handbags",
    "Trolley, Luggage & Suitcases",
    "Formal Shoes",
    "Casual Shoes",
    "Sports Shoes",
    "Outdoor Shoes",
    "Work & Safety Shoes",
    "Ethnic Shoes",
    "Boots",
    "Heels",
    "Contact Lenses",
    "Eye Glasses",
    "Eye Glass Frames",
    "Sunglasses",
    "Contact Lens Cases",
    "Contact Lens Solutions",
    "Contact Lens Tweezers",
    "Eyeglasses Pouches & Cases",
    "Microfiber Wipes",
    "Eyewear Slings",
    "Bracelets",
    "Chains",
    "Mangalsutra",
    "Anklets",
    "Bangles & Bracelets",
    "Necklaces",
    "Earrings",
    "Jewellery Sets",
    "Nosepins & Noserings",
    "Pendants",
    "Rings",
    "Toe Rings",
    "Gold Coins",
    "Brooch"
]